# Site settings
title: Curated list of ReactiveCocoa projects
email: romain.pouclet@gmail.com
description: >
  Curated list of projects using ReactiveCocoa projects.
baseurl: ""
url: "https://racurated.github.io"
twitter_username: ReactiveCocoa
github_username:  ReactiveCocoa

# Build settings
markdown: kramdown
